### ISSUE TITLE
MacOS python3.6 安装报错

### ISSUE THREAD

**Issue by linyongfu2013** [hack12306/12306-booking#12]
MacOS 10.13.4 
python 3.6

```
➜  python source 12306/bin/activate
(12306) ➜  python pip install 12306-booking -U
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting 12306-booking
  Downloading http://mirrors.aliyun.com/pypi/packages/6d/8a/3b85ece5443783fa7bc57a63ff7a5286b3c182102ff5c4604faa6d10648a/12306-booking-0.1.8.tar.gz (69kB)
    100% |████████████████████████████████| 71kB 2.0MB/s
Collecting Pillow>=5.4.1 (from 12306-booking)
  Downloading http://mirrors.aliyun.com/pypi/packages/81/96/05a5c9ba4a75ed330234780e4ae30018bbf77c847982ff6a16b8b291a0da/Pillow-5.4.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.7MB)
    100% |████████████████████████████████| 3.7MB 8.9MB/s
Collecting hack12306>=0.1.11 (from 12306-booking)
  Downloading http://mirrors.aliyun.com/pypi/packages/8f/e6/9333a5e7065e5579fea06c31fcde471d9e6b61a5c8cb3cb55b9b79e15cb4/hack12306-0.1.11.tar.gz
Collecting click==7.0 (from 12306-booking)
  Downloading http://mirrors.aliyun.com/pypi/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
    100% |████████████████████████████████| 81kB 13.4MB/s
Collecting requests>=2.12.4 (from hack12306>=0.1.11->12306-booking)
  Downloading http://mirrors.aliyun.com/pypi/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 9.8MB/s
Collecting BeautifulSoup>=3.2.1 (from hack12306>=0.1.11->12306-booking)
  Downloading http://mirrors.aliyun.com/pypi/packages/1e/ee/295988deca1a5a7accd783d0dfe14524867e31abb05b6c0eeceee49c759d/BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/x8/q83ds71n311bt_4331540p6h0000gn/T/pip-install-dsunu4a1/BeautifulSoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "Unit tests have failed!")?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/x8/q83ds71n311bt_4331540p6h0000gn/T/pip-install-dsunu4a1/BeautifulSoup/

```

**Comment by hotbaby** [comment]
嗯，目前只支持`Python2`
