### ISSUE TITLE
安装出现下面错误

### ISSUE THREAD

**Issue by tonyho** [hack12306/12306-booking#4]
环境Ubuntu 16.04 python

```
 pip3 install 12306-booking 

Collecting 12306-booking
  Using cached https://files.pythonhosted.org/packages/37/f1/f5d6fac51d495bc54cf741b61c07c8f84026f8ab8cf28cd36b09bd886e61/12306-booking-0.1.7.tar.gz
Collecting Pillow>=5.4.1 (from 12306-booking)
  Using cached https://files.pythonhosted.org/packages/8b/e9/5c47710fe383f0582da668302a80a6355fe15c2ce2dde89b50fe34acefa6/Pillow-5.4.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting hack12306>=0.1.11 (from 12306-booking)
  Using cached https://files.pythonhosted.org/packages/8f/e6/9333a5e7065e5579fea06c31fcde471d9e6b61a5c8cb3cb55b9b79e15cb4/hack12306-0.1.11.tar.gz
Collecting click==7.0 (from 12306-booking)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Requirement already satisfied: requests>=2.12.4 in /usr/local/lib/python3.5/dist-packages (from hack12306>=0.1.11->12306-booking) (2.18.4)
Collecting BeautifulSoup>=3.2.1 (from hack12306>=0.1.11->12306-booking)
  Using cached https://files.pythonhosted.org/packages/1e/ee/295988deca1a5a7accd783d0dfe14524867e31abb05b6c0eeceee49c759d/BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-u42wkmkd/BeautifulSoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------

```

**Comment by hotbaby** [comment]
试试`python2`，`python3`没有测试过
