### ISSUE TITLE
python2.7 安装报错

### ISSUE THREAD

**Issue by mengban** [hack12306/12306-booking#8]
ubuntu16.04 python2.7  
python2 -m pip  install 12306-booking 
`
Collecting 12306-booking
  Using cached https://files.pythonhosted.org/packages/6d/8a/3b85ece5443783fa7bc57a63ff7a5286b3c182102ff5c4604faa6d10648a/12306-booking-0.1.8.tar.gz
Collecting Pillow>=5.4.1 (from 12306-booking)
  Using cached https://files.pythonhosted.org/packages/0d/f3/421598450cb9503f4565d936860763b5af413a61009d87a5ab1e34139672/Pillow-5.4.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting hack12306>=0.1.11 (from 12306-booking)
Collecting click==7.0 (from 12306-booking)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting BeautifulSoup>=3.2.1 (from hack12306>=0.1.11->12306-booking)
Collecting requests>=2.12.4 (from hack12306>=0.1.11->12306-booking)
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.12.4->hack12306>=0.1.11->12306-booking)
  Using cached https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.12.4->hack12306>=0.1.11->12306-booking)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests>=2.12.4->hack12306>=0.1.11->12306-booking)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests>=2.12.4->hack12306>=0.1.11->12306-booking)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Building wheels for collected packages: 12306-booking
  Running setup.py bdist_wheel for 12306-booking ... error
  Complete output from command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-52ie6m/12306-booking/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmp1mYiQppip-wheel- --python-tag cp27:
  /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/booking
  copying booking/query.py -> build/lib.linux-x86_64-2.7/booking
  copying booking/utils.py -> build/lib.linux-x86_64-2.7/booking
  copying booking/exceptions.py -> build/lib.linux-x86_64-2.7/booking
  copying booking/pay.py -> build/lib.linux-x86_64-2.7/booking
  copying booking/settings.py -> build/lib.linux-x86_64-2.7/booking
  copying booking/order.py -> build/lib.linux-x86_64-2.7/booking
  copying booking/user.py -> build/lib.linux-x86_64-2.7/booking
  copying booking/run.py -> build/lib.linux-x86_64-2.7/booking
  copying booking/auth.py -> build/lib.linux-x86_64-2.7/booking
  copying booking/_logging.py -> build/lib.linux-x86_64-2.7/booking
  copying booking/__init__.py -> build/lib.linux-x86_64-2.7/booking
  copying booking/command.py -> build/lib.linux-x86_64-2.7/booking
  creating build/lib.linux-x86_64-2.7/tests
  copying tests/__init__.py -> build/lib.linux-x86_64-2.7/tests
  running egg_info
  writing requirements to 12306_booking.egg-info/requires.txt
  writing 12306_booking.egg-info/PKG-INFO
  writing top-level names to 12306_booking.egg-info/top_level.txt
  writing dependency_links to 12306_booking.egg-info/dependency_links.txt
  writing entry points to 12306_booking.egg-info/entry_points.txt
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file '12306_booking.egg-info/SOURCES.txt'
  writing manifest file '12306_booking.egg-info/SOURCES.txt'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-52ie6m/12306-booking/setup.py", line 29, in <module>
      "Operating System :: OS Independent",
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 52, in run
      self.build_package_data()
    File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 107, in build_package_data
      for package, src_dir, build_dir, filenames in self.data_files:
    File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 65, in __getattr__
      self.data_files = self._get_data_files()
    File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 79, in _get_data_files
      return list(map(self._get_pkg_data_files, self.packages or ()))
    File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 91, in _get_pkg_data_files
      for file in self.find_data_files(package, src_dir)
    File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 98, in find_data_files
      + self.package_data.get(package, []))
  TypeError: cannot concatenate 'str' and 'list' objects
  
  ----------------------------------------
  Failed building wheel for 12306-booking
  Running setup.py clean for 12306-booking
Failed to build 12306-booking
Installing collected packages: Pillow, BeautifulSoup, certifi, chardet, idna, urllib3, requests, hack12306, click, 12306-booking
  Running setup.py install for 12306-booking ... error
    Complete output from command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-52ie6m/12306-booking/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-0Jd3DO-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/booking
    copying booking/query.py -> build/lib.linux-x86_64-2.7/booking
    copying booking/utils.py -> build/lib.linux-x86_64-2.7/booking
    copying booking/exceptions.py -> build/lib.linux-x86_64-2.7/booking
    copying booking/pay.py -> build/lib.linux-x86_64-2.7/booking
    copying booking/settings.py -> build/lib.linux-x86_64-2.7/booking
    copying booking/order.py -> build/lib.linux-x86_64-2.7/booking
    copying booking/user.py -> build/lib.linux-x86_64-2.7/booking
    copying booking/run.py -> build/lib.linux-x86_64-2.7/booking
    copying booking/auth.py -> build/lib.linux-x86_64-2.7/booking
    copying booking/_logging.py -> build/lib.linux-x86_64-2.7/booking
    copying booking/__init__.py -> build/lib.linux-x86_64-2.7/booking
    copying booking/command.py -> build/lib.linux-x86_64-2.7/booking
    creating build/lib.linux-x86_64-2.7/tests
    copying tests/__init__.py -> build/lib.linux-x86_64-2.7/tests
    running egg_info
    writing requirements to 12306_booking.egg-info/requires.txt
    writing 12306_booking.egg-info/PKG-INFO
    writing top-level names to 12306_booking.egg-info/top_level.txt
    writing dependency_links to 12306_booking.egg-info/dependency_links.txt
    writing entry points to 12306_booking.egg-info/entry_points.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file '12306_booking.egg-info/SOURCES.txt'
    writing manifest file '12306_booking.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-52ie6m/12306-booking/setup.py", line 29, in <module>
        "Operating System :: OS Independent",
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 52, in run
        self.build_package_data()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 107, in build_package_data
        for package, src_dir, build_dir, filenames in self.data_files:
      File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 65, in __getattr__
        self.data_files = self._get_data_files()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 79, in _get_data_files
        return list(map(self._get_pkg_data_files, self.packages or ()))
      File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 91, in _get_pkg_data_files
        for file in self.find_data_files(package, src_dir)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/build_py.py", line 98, in find_data_files
        + self.package_data.get(package, []))
    TypeError: cannot concatenate 'str' and 'list' objects
    
    ----------------------------------------
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-52ie6m/12306-booking/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-0Jd3DO-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-52ie6m/12306-booking/
`

**Comment by hotbaby** [comment]
Linux系统安装问题已修复，可以更新到`0.1.12`版本再试试 @mengban
