### ISSUE TITLE
安装正常 执行报错找不到six模块

### ISSUE THREAD

**Issue by bekylin** [hack12306/12306-booking#9]
环境
- mac OS 10.14.2
- python_version = "2.7" 

安装过程和报错信息: 
```
[~/codelife/12306booking]$ pipenv --python 2
Creating a virtualenv for this project…
Using /usr/bin/python to create virtualenv…
⠋Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /User/home/.local/share/virtualenvs/12306booking-8aqe4YCo/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /User/home/.local/share/virtualenvs/12306booking-8aqe4YCo
Creating a Pipfile for this project…
[~/codelife/12306booking]$ pipenv shell
Spawning environment shell (/bin/zsh). Use 'exit' to leave.
source /User/home/.local/share/virtualenvs/12306booking-8aqe4YCo/bin/activate
[~/codelife/12306booking]$ source /User/home/.local/share/virtualenvs/12306booking-8aqe4YCo/bin/activate
(12306booking-8aqe4YCo) [~/codelife/12306booking]$ pip install 12306-booking
Collecting 12306-booking
  Downloading https://files.pythonhosted.org/packages/6d/8a/3b85ece5443783fa7bc57a63ff7a5286b3c182102ff5c4604faa6d10648a/12306-booking-0.1.8.tar.gz (69kB)
    100% |████████████████████████████████| 71kB 271kB/s
Collecting Pillow>=5.4.1 (from 12306-booking)
  Downloading https://files.pythonhosted.org/packages/7e/bb/d502ae951099ce9a5a20dec21e577f304b7706321f83205c5215ebc028cd/Pillow-5.4.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.7MB)
    100% |████████████████████████████████| 3.7MB 135kB/s
Collecting hack12306>=0.1.11 (from 12306-booking)
  Downloading https://files.pythonhosted.org/packages/8f/e6/9333a5e7065e5579fea06c31fcde471d9e6b61a5c8cb3cb55b9b79e15cb4/hack12306-0.1.11.tar.gz
Collecting click==7.0 (from 12306-booking)
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
    100% |████████████████████████████████| 81kB 114kB/s
Collecting requests>=2.12.4 (from hack12306>=0.1.11->12306-booking)
  Downloading https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 106kB/s
Collecting BeautifulSoup>=3.2.1 (from hack12306>=0.1.11->12306-booking)
  Downloading https://files.pythonhosted.org/packages/1e/ee/295988deca1a5a7accd783d0dfe14524867e31abb05b6c0eeceee49c759d/BeautifulSoup-3.2.1.tar.gz
Collecting urllib3<1.25,>=1.21.1 (from requests>=2.12.4->hack12306>=0.1.11->12306-booking)
  Downloading https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl (118kB)
    100% |████████████████████████████████| 122kB 170kB/s
Collecting certifi>=2017.4.17 (from requests>=2.12.4->hack12306>=0.1.11->12306-booking)
  Downloading https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 225kB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.12.4->hack12306>=0.1.11->12306-booking)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 208kB/s
Collecting idna<2.9,>=2.5 (from requests>=2.12.4->hack12306>=0.1.11->12306-booking)
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 161kB/s
Building wheels for collected packages: 12306-booking, hack12306, BeautifulSoup
  Running setup.py bdist_wheel for 12306-booking ... done
  Stored in directory: /User/home/Library/Caches/pip/wheels/1e/62/71/1d1ba512ea83693ccea926a25771dd7045687ed0d89c6d4c61
  Running setup.py bdist_wheel for hack12306 ... done
  Stored in directory: /User/home/Library/Caches/pip/wheels/b8/77/a7/fc8c50ed3e78e56f19cf7816dc072461d15d9c08599a0b1054
  Running setup.py bdist_wheel for BeautifulSoup ... done
  Stored in directory: /User/home/Library/Caches/pip/wheels/74/d2/0b/8ef02aab9e15c6e5158d7aee909adab931a9c54920e99f468e
Successfully built 12306-booking hack12306 BeautifulSoup
Installing collected packages: Pillow, urllib3, certifi, chardet, idna, requests, BeautifulSoup, hack12306, click, 12306-booking
Successfully installed 12306-booking-0.1.8 BeautifulSoup-3.2.1 Pillow-5.4.1 certifi-2018.11.29 chardet-3.0.4 click-7.0 hack12306-0.1.11 idna-2.8 requests-2.21.0 urllib3-1.24.1
(12306booking-8aqe4YCo) [~/codelife/12306booking]$
(12306booking-8aqe4YCo) [~/codelife/12306booking]$ 12306-booking
Traceback (most recent call last):
  File "/User/home/.local/share/virtualenvs/12306booking-8aqe4YCo/bin/12306-booking", line 7, in <module>
    from booking.command import booking
  File "/User/home/.local/share/virtualenvs/12306booking-8aqe4YCo/lib/python2.7/site-packages/booking/command.py", line 16, in <module>
    from .run import initialize, run as booking_run_loop
  File "/User/home/.local/share/virtualenvs/12306booking-8aqe4YCo/lib/python2.7/site-packages/booking/run.py", line 16, in <module>
    from hack12306.constants import (BANK_ID_WX, BANK_ID_MAP, SEAT_TYPE_CODE_MAP,)
  File "/User/home/.local/share/virtualenvs/12306booking-8aqe4YCo/lib/python2.7/site-packages/hack12306/__init__.py", line 11, in <module>
    from .pay import TrainPayAPI
  File "/User/home/.local/share/virtualenvs/12306booking-8aqe4YCo/lib/python2.7/site-packages/hack12306/pay.py", line 19, in <module>
    from .base import TrainBaseAPI
  File "/User/home/.local/share/virtualenvs/12306booking-8aqe4YCo/lib/python2.7/site-packages/hack12306/base.py", line 23, in <module>
    from .utils import urlencode, tomorrow, time_cst_format
  File "/User/home/.local/share/virtualenvs/12306booking-8aqe4YCo/lib/python2.7/site-packages/hack12306/utils.py", line 10, in <module>
    import six
ImportError: No module named six
```

执行`pip install 12306-booking -U`: 
```terminal
(12306booking-8aqe4YCo) [~/codelife/12306booking]$ pip install 12306-booking -U
Requirement already up-to-date: 12306-booking in ~/xxx/virtualenvs/12306booking-8aqe4YCo/lib/python2.7/site-packages (0.1.8)
Requirement already satisfied, skipping upgrade: hack12306>=0.1.11 in ~/xxx/virtualenvs/12306booking-8aqe4YCo/lib/python2.7/site-packages (from 12306-booking) (0.1.11)
Requirement already satisfied, skipping upgrade: Pillow>=5.4.1 in ~/xxx/virtualenvs/12306booking-8aqe4YCo/lib/python2.7/site-packages (from 12306-booking) (5.4.1)
Requirement already satisfied, skipping upgrade: click==7.0 in ~/xxx/virtualenvs/12306booking-8aqe4YCo/lib/python2.7/site-packages (from 12306-booking) (7.0)
Requirement already satisfied, skipping upgrade: requests>=2.12.4 in ~/xxx/virtualenvs/12306booking-8aqe4YCo/lib/python2.7/site-packages (from hack12306>=0.1.11->12306-booking) (2.21.0)
Requirement already satisfied, skipping upgrade: BeautifulSoup>=3.2.1 in ~/xxx/virtualenvs/12306booking-8aqe4YCo/lib/python2.7/site-packages (from hack12306>=0.1.11->12306-booking) (3.2.1)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in ~/xxx/virtualenvs/12306booking-8aqe4YCo/lib/python2.7/site-packages (from requests>=2.12.4->hack12306>=0.1.11->12306-booking) (1.24.1)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in ~/xxx/virtualenvs/12306booking-8aqe4YCo/lib/python2.7/site-packages (from requests>=2.12.4->hack12306>=0.1.11->12306-booking) (2018.11.29)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in ~/xxx/virtualenvs/12306booking-8aqe4YCo/lib/python2.7/site-packages (from requests>=2.12.4->hack12306>=0.1.11->12306-booking) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in ~/xxx/virtualenvs/12306booking-8aqe4YCo/lib/python2.7/site-packages (from requests>=2.12.4->hack12306>=0.1.11->12306-booking) (2.8)
```

**Comment by hotbaby** [comment]
程序bug，再更新下程序试试。`pip install 12306-booking -U --user`

**Comment by hotbaby** [comment]
fixed
